/**
 * Calendar | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CalendarTask } from './calendarTask';
import { ApiSubjectsIdGetIdParameter } from './apiSubjectsIdGetIdParameter';
import { Subject } from './subject';


export interface User { 
    uid?: ApiSubjectsIdGetIdParameter;
    email?: string;
    passhash?: string;
    name?: string | null;
    subjects?: Array<Subject>;
    calendarTask?: Array<CalendarTask>;
}

