/**
 * Calendar | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CalendarTaskSubid } from './calendarTaskSubid';
import { User } from './user';
import { ApiSubjectsIdGetIdParameter } from './apiSubjectsIdGetIdParameter';
import { Subject } from './subject';


export interface CalendarTask { 
    id?: ApiSubjectsIdGetIdParameter;
    userId?: ApiSubjectsIdGetIdParameter;
    subid?: CalendarTaskSubid | null;
    title?: string;
    description?: string | null;
    startTime?: string | null;
    endTime?: string | null;
    isCompleted?: boolean | null;
    source?: string | null;
    sub?: Subject | null;
    user?: User;
}

