/**
 * Calendar | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';
import { CalendarTask } from './calendarTask';
import { ApiSubjectsIdGetIdParameter } from './apiSubjectsIdGetIdParameter';


export interface Subject { 
    subid?: ApiSubjectsIdGetIdParameter;
    userId?: ApiSubjectsIdGetIdParameter;
    name?: string;
    colorCode?: string | null;
    teacherEmail?: string | null;
    groupNumber?: string | null;
    calendarTask?: Array<CalendarTask>;
    user?: User;
}

